//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomServiceTestUtil.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomServiceTestUtil.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomServiceTestUtil.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}.{1}.
        /// </summary>
        internal static string BaseURLString {
            get {
                return ResourceManager.GetString("BaseURLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling with file {0}.
        /// </summary>
        internal static string CallingWithFile {
            get {
                return ResourceManager.GetString("CallingWithFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling without parameters.
        /// </summary>
        internal static string CallingWithoutParameters {
            get {
                return ResourceManager.GetString("CallingWithoutParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling with parameters: {0} {1}.
        /// </summary>
        internal static string CallingWithParameters {
            get {
                return ResourceManager.GetString("CallingWithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Called from test tool.
        /// </summary>
        internal static string CallPerformed {
            get {
                return ResourceManager.GetString("CallPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call.
        /// </summary>
        internal static string CallService {
            get {
                return ResourceManager.GetString("CallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The call to the service finished in {0} seconds.
        /// </summary>
        internal static string CallTiming {
            get {
                return ResourceManager.GetString("CallTiming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration error.
        /// </summary>
        internal static string ConfigurationError {
            get {
                return ResourceManager.GetString("ConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm action.
        /// </summary>
        internal static string ConfirmAction {
            get {
                return ResourceManager.GetString("ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected endpoint setup will be permanently removed ({0}) Continue?.
        /// </summary>
        internal static string ConfirmRemoval {
            get {
                return ResourceManager.GetString("ConfirmRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter {0} with value {1} will be permanently removed, continue?.
        /// </summary>
        internal static string ConfirmRemovalOfParm {
            get {
                return ResourceManager.GetString("ConfirmRemovalOfParm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm removal of {0}.
        /// </summary>
        internal static string ConfirmRemovalOfService {
            get {
                return ResourceManager.GetString("ConfirmRemovalOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The JSON string is modified, do you wish to save it?.
        /// </summary>
        internal static string ConfirmSaveJSON {
            get {
                return ResourceManager.GetString("ConfirmSaveJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This machine is already configured ({0} - {1}), check your input and try again.
        /// </summary>
        internal static string DuplicateMachine {
            get {
                return ResourceManager.GetString("DuplicateMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varning, vissa bilder kan vara stötande, känsliga personer avråds att fortsätta, vill du verkligen se eländet?.
        /// </summary>
        internal static string EasterEgg {
            get {
                return ResourceManager.GetString("EasterEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestEndPointsV2.json.
        /// </summary>
        internal static string EndPoints {
            get {
                return ResourceManager.GetString("EndPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is created and saved.
        /// </summary>
        internal static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP status code: .
        /// </summary>
        internal static string HTTPStatusCode {
            get {
                return ResourceManager.GetString("HTTPStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Input file successfully serialized to JSON string.
        /// </summary>
        internal static string InputFileSerialized {
            get {
                return ResourceManager.GetString("InputFileSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon json_egi_icon {
            get {
                object obj = ResourceManager.GetObject("json_egi_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Files (*.json)|*.json.
        /// </summary>
        internal static string JSONFileFilter {
            get {
                return ResourceManager.GetString("JSONFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \nJSON serialized to string:\n{0}.
        /// </summary>
        internal static string JSONSerialized {
            get {
                return ResourceManager.GetString("JSONSerialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json.
        /// </summary>
        internal static string JSONSuffix {
            get {
                return ResourceManager.GetString("JSONSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick service, server, options and parameters and JSON File (if needed) for your call. Click the button Call Service to make the call.
        /// </summary>
        internal static string MainInstructions {
            get {
                return ResourceManager.GetString("MainInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Service Test Util.
        /// </summary>
        internal static string MyDocumentsFolderName {
            get {
                return ResourceManager.GetString("MyDocumentsFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select if the service should be called with parameters, file or none.
        /// </summary>
        internal static string NoCallParameterSelected {
            get {
                return ResourceManager.GetString("NoCallParameterSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NoSchema {
            get {
                return ResourceManager.GetString("NoSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all required parameters to test a service: 
        ///
        ///1. Service 
        ///2. Machine
        ///3. Input option.
        /// </summary>
        internal static string NotPossibleToCall {
            get {
                return ResourceManager.GetString("NotPossibleToCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the response button to open the response.
        /// </summary>
        internal static string OpenTheResponse {
            get {
                return ResourceManager.GetString("OpenTheResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON file.
        /// </summary>
        internal static string OptionJSONFile {
            get {
                return ResourceManager.GetString("OptionJSONFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No parameters.
        /// </summary>
        internal static string OptionNoParameters {
            get {
                return ResourceManager.GetString("OptionNoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set parameters.
        /// </summary>
        internal static string OptionParameters {
            get {
                return ResourceManager.GetString("OptionParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure processing : .
        /// </summary>
        internal static string ProcessingFailure {
            get {
                return ResourceManager.GetString("ProcessingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request: .
        /// </summary>
        internal static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response: .
        /// </summary>
        internal static string Response {
            get {
                return ResourceManager.GetString("Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string ResponseFolder {
            get {
                return ResourceManager.GetString("ResponseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response from the method call is saved to: &quot;{0}&quot; {1}File: &quot;{2}&quot;.
        /// </summary>
        internal static string ResponseSaved {
            get {
                return ResourceManager.GetString("ResponseSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tmpResponse.json.
        /// </summary>
        internal static string ResponseTmpFile {
            get {
                return ResourceManager.GetString("ResponseTmpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string SchemaFolder {
            get {
                return ResourceManager.GetString("SchemaFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory setup for the schemas does not exist, go to settings and set a valid path.
        /// </summary>
        internal static string SchemaPathInvalid {
            get {
                return ResourceManager.GetString("SchemaPathInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema path is missing, set up the path to the schemas in the application settings.
        /// </summary>
        internal static string SchemaPathMissing {
            get {
                return ResourceManager.GetString("SchemaPathMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Validation on: {1}.
        /// </summary>
        internal static string SchemaValidation {
            get {
                return ResourceManager.GetString("SchemaValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have configured the service to validate the response with a schema but the schema is not present in the schema directory, add the schema to the folder {0} or remove the validation from the service.
        /// </summary>
        internal static string SchemaValidationNotPossible {
            get {
                return ResourceManager.GetString("SchemaValidationNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the option to use for the call.
        /// </summary>
        internal static string SelectAnOption {
            get {
                return ResourceManager.GetString("SelectAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServicesAPIV2.json.
        /// </summary>
        internal static string ServiceAPI {
            get {
                return ResourceManager.GetString("ServiceAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        internal static string ServiceResponse {
            get {
                return ResourceManager.GetString("ServiceResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\tmpResponse.json.
        /// </summary>
        internal static string TemJSONFIle {
            get {
                return ResourceManager.GetString("TemJSONFIle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestServerSettings.json.
        /// </summary>
        internal static string TestServerSettings {
            get {
                return ResourceManager.GetString("TestServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iStone test service.
        /// </summary>
        internal static string TestServiceEvent {
            get {
                return ResourceManager.GetString("TestServiceEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}The schema validation failed - The service will not be called.
        /// </summary>
        internal static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        internal static string ValidationFolder {
            get {
                return ResourceManager.GetString("ValidationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response is validated ok against schema {0} {1}.
        /// </summary>
        internal static string ValidationOK {
            get {
                return ResourceManager.GetString("ValidationOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The validation result from the method call is saved to: &quot;{0}&quot; {1}File: &quot;{2}&quot;.
        /// </summary>
        internal static string ValidationSaved {
            get {
                return ResourceManager.GetString("ValidationSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong use of this function {0}.
        /// </summary>
        internal static string WrongUseOfFunction {
            get {
                return ResourceManager.GetString("WrongUseOfFunction", resourceCulture);
            }
        }
    }
}
